name: site_see
description: "Project for HackTheMountain"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.11.5

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.3.0       # Carte interactive OpenStreetMap
  latlong2: ^0.9.1          # Types de coordonnées GPS
  geolocator: ^14.0.2       # Accès au GPS du téléphone

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Adding the firebase core elements
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  image: ^4.2.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
    - family: DM Mono
      fonts:
        - asset: assets/fonts/DMMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMMono-Medium.ttf
          weight: 500